#!/bin/sh
set -e

dpkg-source --before-build `pwd`
dpkg-buildpackage -rfakeroot --target=pre-build
dpkg-buildpackage -rfakeroot --target=common-configure-arch 2>/dev/null
make -C lib
make -C tests check-am
